/** @type {import('tailwindcss').Config} */
/**
 * Tema Tailwind + DaisyUI. Espaçamentos semânticos de painel (`gap-tasks-panel*`) e raios do app
 * vivem em `index.css` como variáveis (`--tasks-panel-gap`, `--rounded-box`, …), não duplicados aqui.
 * Tokens gerados pelo Style Dictionary entram via CSS vars em `index.css`; `tokens/tailwind.config.tokens.js`
 * existe para builds que mesclam cores/fontes quando disponíveis.
 */

// Tenta importar tokens gerados (opcional - fallback para valores padrão)
// Nota: Se tokens não existirem, usa valores padrão do CSS
let designTokens = {};
try {
  // Importação síncrona não funciona com ES modules, então usamos valores padrão
  // Os tokens serão aplicados via CSS variables no index.css
} catch (error) {
  // Se tokens não existirem, usa valores padrão
}

/** Tema escuro (DaisyUI) alinhado à paleta shadcn-style fornecida — mesmas chaves semânticas. */
const dimTheme = {
  default: false,
  prefersdark: false,
  "color-scheme": "dark",
  "base-100": "#15161a",
  "base-200": "#1c1d22",
  "base-300": "#2c2e34",
  "base-content": "#f0f0f0",
  "primary": "#8c5cff",
  "primary-content": "#ffffff",
  "secondary": "#25262c",
  "secondary-content": "#f0f0f0",
  "accent": "#1e293b",
  "accent-content": "#79c0ff",
  "neutral": "#25262c",
  "neutral-content": "#f0f0f0",
  "info": "#5993f4",
  "info-content": "#ffffff",
  "success": "#4ade80",
  "success-content": "#14532d",
  "warning": "#fca5a5",
  "warning-content": "#15161a",
  "error": "#f87171",
  "error-content": "#ffffff",
  "--radius-selector": "1.4rem",
  "--radius-field": "1.4rem",
  "--radius-box": "1.4rem",
  "--rounded-btn": "1.4rem",
  "--rounded-badge": "1.4rem",
  "--tab-radius": "1.4rem",
  "--size-selector": "0.1875rem",
  "--size-field": "0.1875rem",
  "--border": "1px",
  "--depth": "0",
  "--noise": "0",
};

export default {
  darkMode: 'class',
  safelist: [
    'task-details-neu-modal',
    'task-details-neu-raised',
    'task-details-neu-inset',
    'task-details-neu-inset-deep',
    'task-details-neu-track',
    'task-details-neu-chip',
    'task-details-neu-chip--active',
    'task-details-neu-chip--status-active',
    'task-details-neu-tab',
    'task-details-neu-status-pill',
    'task-details-neu-ghost-btn',
    'task-details-neu-jira-btn',
    'task-details-neu-description',
    'task-details-neu-watchers',
    'task-details-neu-roteiro-shell',
    'task-details-neu-roteiro-header',
    'task-details-neu-roteiro-block',
    'task-details-neu-roteiro-inner',
    'task-details-neu-exec-badge',
    'task-details-neu-tab-count',
    'task-details-neu-header-section',
    'task-list-neu-badge',
    'task-list-neu-badge--info',
    'task-list-neu-badge--error',
    'task-list-neu-badge--success',
    'task-list-neu-badge--primary',
    'task-list-neu-badge--neutral',
    'task-list-neu-badge--tech',
    'task-details-neu-select',
    'task-details-neu-textarea',
    'task-details-neu-status-btn',
    'leve-neu-inset-content',
    'leve-modal-neu-shell',
    'app-header-neu-track',
    'app-header-neu-track-separator',
    'app-header-neu-chip',
    'app-header-neu-chip--active',
    'app-header-neu-nav-pill',
    'app-header-neu-toolbar-pill',
    'app-header-neu-toolbar-pill--primary',
    'app-header-neu-toolbar-pill--secondary',
    'create-project-neu-modal',
    'create-project-neu-option',
    'create-project-neu-input',
    'create-project-neu-inset',
    'create-project-neu-chip',
    'create-project-neu-btn-primary',
    'dashboard-neu-scope',
    'dashboard-neu-filter-toolbar',
    'dashboard-neu-filter-btn',
    'dashboard-neu-filter-btn--active',
    'dashboard-neu-action-btn',
    'dashboard-neu-donut-well',
    'documents-view-scope',
    'documents-neu-section',
    'documents-neu-panel',
    'documents-neu-card',
    'documents-neu-chip',
    'documents-neu-btn-primary',
    'documents-neu-filter-track',
    'documents-neu-filter-pill',
    'documents-neu-search',
    'documents-neu-summary-track',
    'documents-neu-alert-success',
    'documents-neu-alert-info',
    'documents-neu-progress-track',
    'documents-neu-progress-fill',
    'documents-neu-list-track',
    'documents-card-neu-raised',
    'documents-category-badge--requisitos',
    'documents-neu-spec-remove',
    'business-rules-view-scope',
    'settings-view-scope',
    'settings-neu-modal',
    'leve-settings-tabs-track',
    'leve-settings-prefs-tabs-track',
    'leve-settings-tab--active',
    'leve-settings-section-icon-wrap',
    'leve-settings-inset-panel',
    'settings-neu-configured-panel',
    'settings-neu-kbd',
    'settings-neu-edit-btn',
    'settings-neu-remove-btn',
    'settings-neu-action-btn',
    'business-rules-neu-list-track',
    'business-rules-neu-card',
    'business-rules-neu-inset',
    'business-rules-neu-chip',
    'business-rules-neu-category-badge',
    'business-rules-neu-category-badge--primary',
    'business-rules-neu-category-badge--secondary',
    'business-rules-neu-category-badge--accent',
    'business-rules-neu-category-badge--info',
    'business-rules-neu-category-badge--success',
    'business-rules-neu-category-badge--warning',
    'business-rules-neu-category-badge--purple',
    'documents-neu-inset',
    'documents-card-actions',
    'documents-card-action-btn',
    'documents-card-action-outline',
    'documents-card-action-primary',
    'documents-card-action-remove',
    'test-strategy-neu-card',
    'test-strategy-neu-inset',
    'test-strategy-neu-toggle',
    'test-strategy-neu-tool-chip',
    'test-strategy-neu-tool-input',
    'test-case-detail-level-track',
    'test-case-detail-level-option',
    'test-case-detail-level-option--active',
    'task-details-neu-primary-cta',
    'test-report-neu-modal',
    'test-report-neu-section',
    'test-report-neu-inset',
    'test-report-neu-chip-btn',
    'test-report-neu-primary-btn',
    'test-report-neu-format-option',
    'test-report-neu-format-option--active',
    'test-report-neu-format-idle',
    'test-report-neu-stat-card',
    'test-report-neu-preview-field',
    'test-report-generate-record-btn',
    'workspace-panel-neu-shell',
    'workspace-panel-neu-metric-tile',
    'workspace-panel-neu-icon-wrap',
    'workspace-panel-neu-dist-track',
    'projects-dashboard-sidebar-panel',
    'projects-dashboard-hero-chrome',
    'projects-dashboard-page-surface',
    'app-dark-page-surface',
    'app-dark-neu-root',
    'app-neu-action-track',
    'app-neu-action-btn',
    'app-neu-action-btn--active',
    'app-neu-action-icon-wrap',
    'app-neu-action-divider',
    'app-neu-action-btn--danger',
    'business-rules-card-action-edit',
    'business-rules-card-action-delete',
    'app-dark-hero-chrome',
    '!bg-[#4B433D]',
  ],
  content: [
    "./index.html",
    "./index.{js,ts,jsx,tsx}",
    "./App.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
    "./api/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./stories/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'sm': '640px',   // Tablet pequeno
      'md': '768px',   // Tablet
      'lg': '1024px',  // Desktop pequeno - PRIORIDADE WEB
      'xl': '1280px',  // Desktop - PRIORIDADE WEB
      '2xl': '1536px', // Desktop grande
    },
    extend: {
      fontFamily: {
        ...(designTokens.fontFamily || {}),
        sans: designTokens.fontFamily?.sans || ['Segoe UI Variable', 'Segoe UI', 'sans-serif'],
        heading: designTokens.fontFamily?.heading || ['Poppins', 'Montserrat', 'Segoe UI Variable', 'Segoe UI', 'sans-serif'],
        body: designTokens.fontFamily?.body || ['Inter', 'Segoe UI Variable', 'Segoe UI', 'sans-serif'],
      },
      colors: {
        ...(designTokens.colors || {}),
        // Cores da marca (Documentos / referencial)
        'brand-purple': '#6366f1',
        'brand-orange': 'rgb(251 76 0)',
        'brand-orange-selected': 'rgb(251 76 0)',
        'brand-orange-selected-hover': 'rgb(224 69 0)',
        'brand-blue': '#0ea5e9',
        // Aliases utilitários (não conflitam com DaisyUI)
        // Obs: DaisyUI expõe tokens via CSS vars (ex.: --b1/--b2/--b3/--bc/--er)
        danger: 'oklch(var(--er) / <alpha-value>)',
        surface: {
          DEFAULT: 'oklch(var(--b1) / <alpha-value>)',
          border: 'oklch(var(--b3) / <alpha-value>)',
          hover: 'oklch(var(--b2) / <alpha-value>)',
        },
        background: 'oklch(var(--b1) / <alpha-value>)',
        'text-primary': 'oklch(var(--bc) / <alpha-value>)',
        /** ~4.5:1 em fundos claros comuns (WCAG AA corpo) */
        'text-secondary': 'oklch(var(--bc) / 0.78)',
        'text-tertiary': 'oklch(var(--bc) / 0.64)',
        muted: 'oklch(var(--bc) / 0.6)',
      },
      spacing: {
        ...(designTokens.spacing || {}),
        'xs': designTokens.spacing?.xs || 'var(--spacing-xs)',
        'sm': designTokens.spacing?.sm || 'var(--spacing-sm)',
        'md': designTokens.spacing?.md || 'var(--spacing-md)',
        'lg': designTokens.spacing?.lg || 'var(--spacing-lg)',
        'xl': designTokens.spacing?.xl || 'var(--spacing-xl)',
        '2xl': designTokens.spacing?.['2xl'] || 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
      },
      fontSize: {
        'h1': 'var(--fs-h1)',
        'h2': 'var(--fs-h2)',
        'h3': 'var(--fs-h3)',
        'h4': 'var(--fs-h4)',
        'body': 'var(--fs-body)',
        'small': 'var(--fs-small)',
        'label': 'var(--fs-label)',
      },
      lineHeight: {
        'tight': 'var(--lh-tight)',
        'normal': 'var(--lh-normal)',
        'comfortable': 'var(--lh-comfortable)',
        'relaxed': 'var(--lh-relaxed)',
      },
      borderRadius: {
        ...(designTokens.borderRadius || {}),
        'leve-sm': designTokens.borderRadius?.sm || 'var(--radius-sm)',
        'leve-md': designTokens.borderRadius?.md || 'var(--radius-md)',
        'leve-lg': designTokens.borderRadius?.lg || 'var(--radius-lg)',
        'leve-xl': designTokens.borderRadius?.xl || 'var(--radius-xl)',
      },
      boxShadow: {
        ...(designTokens.boxShadow || {}),
      },
    }
  },
  plugins: [
    require('daisyui'),
    require('tailwindcss-animate'),
    require('tailwind-scrollbar'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          "base-100": "oklch(98% 0 0)",
          "base-200": "#e8e8ea",
          "base-300": "#e0e0e3",
          "base-content": "#451e44",
          "primary": "#fb4c00",
          "primary-content": "oklch(100% 0 0)",
          "secondary": "#451e44",
          "secondary-content": "oklch(100% 0 0)",
          "accent": "#451e44",
          "accent-content": "#fcf9ec",
          "neutral": "#fcf9ec",
          "neutral-content": "#451e44",
          "info": "#fb4c00",
          "info-content": "#451e44",
          "success": "oklch(59% 0.145 163.225)",
          "success-content": "oklch(98% 0.003 247.858)",
          /** Antes `#f2f2f2`: `text-warning` ficava ilegível em cards claros (warning é cor de frente no Daisy). */
          "warning": "#ca8a04",
          "warning-content": "#422006",
          "error": "oklch(50% 0.213 27.518)",
          "error-content": "oklch(98% 0.003 247.858)",
          "--rounded-box": "2rem",
          "--rounded-btn": "2rem",
          "--rounded-badge": "2rem",
          "--tab-radius": "2rem",
        },
      },
      {
        dark: dimTheme,
      },
      {
        dim: dimTheme,
      },
    ],
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}
