
export interface TestCase {
  id: string;
  description: string;
  steps: string[];
  expectedResult: string;
  status: 'Not Run' | 'Passed' | 'Failed';
  strategies?: string[];
  executedStrategy?: string | string[]; // Suporta string (legado) ou array (novo formato)
  isAutomated?: boolean;
  observedResult?: string;
  toolsUsed?: string[]; // Ferramentas utilizadas neste caso de teste
  preconditions?: string; // Précondições
  testSuite?: string; // Suite de teste
  testEnvironment?: string; // Ambiente de teste
}

export type TestCaseDetailLevel = 'Resumido' | 'Padrão' | 'Detalhado';

export type JiraTaskType = 'Epic' | 'História' | 'Tarefa' | 'Bug';

export type BugSeverity = 'Crítico' | 'Alto' | 'Médio' | 'Baixo';

export type TeamRole = 'Product' | 'QA' | 'Dev';

export type TaskPriority = 'Baixa' | 'Média' | 'Alta' | 'Urgente';

export type STLCPhaseName = 
  | 'Análise de Requisitos'
  | 'Planejamento de Testes'
  | 'Desenvolvimento de Casos de Teste'
  | 'Execução de Testes'
  | 'Encerramento do Teste';

export type RequirementType = 'Funcional' | 'Não Funcional';

export type RequirementStatus = 'Rascunho' | 'Aprovado' | 'Em Teste' | 'Validado';

export interface RequirementAIAnalysis {
  qualityScore: number; // 0-100
  completeness: string; // Análise de completude
  clarity: string; // Análise de clareza
  testability: string; // Análise de testabilidade
  suggestedImprovements: string[]; // Melhorias sugeridas
  detectedGaps: string[]; // Gaps detectados
  generatedAt: string;
}

export interface Requirement {
  id: string; // ex: "R-001"
  title: string;
  description: string;
  type: RequirementType;
  priority: TaskPriority;
  stlcPhase: STLCPhaseName; // Fase do STLC associada
  acceptanceCriteria: string[];
  relatedTasks: string[]; // IDs de tarefas relacionadas
  testCases: string[]; // IDs de casos de teste que validam
  status: RequirementStatus;
  createdAt: string;
  updatedAt: string;
  sourceTaskId?: string; // ID da tarefa que originou o requisito
  autoGenerated?: boolean; // Indica se foi gerado automaticamente
  aiAnalysis?: RequirementAIAnalysis; // Análise de IA do requisito
}

export interface RTMEntry {
  requirementId: string;
  testCaseIds: string[];
  coverage: number; // 0-100
  lastValidated: string;
}

export interface TestStrategy {
  testType: string;
  description: string;
  howToExecute: string[];
  tools: string;
}

export interface BddScenario {
  id: string;
  title: string;
  gherkin: string;
}

export interface TaskIAAnalysis {
  taskId: string;
  summary: string;
  detectedProblems: string[];
  riskLevel: 'Baixo' | 'Médio' | 'Alto' | 'Crítico';
  riskScore: number; // 0-100
  missingItems: string[];
  bddSuggestions: string[];
  qaImprovements: string[];
  generatedAt: string;
  isOutdated?: boolean;
}

export interface TestIAAnalysis {
  testId: string;
  taskId: string;
  summary: string;
  coverage: string;
  detectedProblems: string[];
  suggestions: string[];
  generatedAt: string;
  isOutdated?: boolean;
}

export interface GeneralIAAnalysis {
  summary: string;
  detectedProblems: string[];
  riskCalculation: {
    overallRisk: 'Baixo' | 'Médio' | 'Alto' | 'Crítico';
    riskScore: number; // 0-100
    riskFactors: Array<{
      factor: string;
      impact: 'Baixo' | 'Médio' | 'Alto';
      description: string;
    }>;
  };
  missingItems: string[];
  bddSuggestions: Array<{
    taskId: string;
    taskTitle: string;
    scenarios: string[];
  }>;
  qaImprovements: string[];
  taskAnalyses: TaskIAAnalysis[];
  testAnalyses: TestIAAnalysis[];
  generatedAt: string;
  isOutdated?: boolean;
}

export interface JiraTask {
  id: string;
  title: string;
  description: string;
  status: 'To Do' | 'In Progress' | 'Done';
  jiraStatus?: string; // Status original do Jira (ex: "Em Andamento", "Concluído", etc.)
  testCases: TestCase[];
  testStrategy?: TestStrategy[];
  type: JiraTaskType;
  parentId?: string;
  bddScenarios?: BddScenario[];
  severity?: BugSeverity;
  priority?: TaskPriority;
  createdAt?: string; // ISO string
  completedAt?: string; // ISO string
  owner?: TeamRole;
  assignee?: TeamRole;
  tags?: string[];
  dependencies?: string[]; // IDs de tarefas que bloqueiam esta
  comments?: Comment[];
  attachments?: Attachment[];
  estimatedHours?: number;
  actualHours?: number;
  checklist?: ChecklistItem[];
  iaAnalysis?: TaskIAAnalysis;
  toolsUsed?: string[]; // Ferramentas utilizadas nesta task
  executedStrategies?: number[]; // Índices das estratégias que foram executadas
  strategyTools?: { [strategyIndex: number]: string[] }; // Ferramentas utilizadas por estratégia (índice -> ferramentas)
  isEscapedDefect?: boolean; // Indica se o bug foi vazado para produção
}

// Ferramentas sugeridas para testes
export const SUGGESTED_TOOLS = [
  'Postman',
  'Insomnia',
  'DBeaver',
  'Kibana'
] as const;

export type SuggestedTool = typeof SUGGESTED_TOOLS[number];

export interface ProjectDocument {
  name: string;
  content: string;
  analysis?: string;
}

export type PhaseStatus = 'Não Iniciado' | 'Em Andamento' | 'Concluído';

export type PhaseName =
  | 'Request'
  | 'Analysis'
  | 'Design'
  | 'Analysis and Code'
  | 'Build'
  | 'Test'
  | 'Release'
  | 'Deploy'
  | 'Operate'
  | 'Monitor';

export interface Phase {
  name: PhaseName;
  status: PhaseStatus;
  summary?: string;
  testTypes?: string[];
}

export interface ShiftLeftRecommendation {
  phase: 'Analysis' | 'Design' | 'Analysis and Code';
  recommendation: string;
}

export interface ShiftLeftAnalysis {
  recommendations: ShiftLeftRecommendation[];
}

export interface TestPyramidLevel {
  level: 'Unitário' | 'Integração' | 'E2E';
  effort: string;
  examples: string[];
}

export interface TestPyramidAnalysis {
  distribution: TestPyramidLevel[];
}

export interface DashboardOverviewAnalysis {
  summary: string; // Resumo executivo
  currentPhase: string; // Análise da fase atual
  metrics: {
    analysis: string; // Análise das métricas do projeto
    strengths: string[]; // Pontos fortes identificados
    weaknesses: string[]; // Pontos fracos identificados
  };
  risks: string[]; // Riscos identificados
  recommendations: string[]; // Recomendações
  generatedAt: string;
  isOutdated?: boolean;
}

export interface DashboardRequirementsAnalysis {
  summary: string;
  coverage: {
    analysis: string; // Análise de cobertura RTM
    percentage: number; // Percentual de cobertura
    gaps: string[]; // Gaps de cobertura identificados
  };
  quality: {
    analysis: string; // Análise de qualidade dos requisitos
    issues: string[]; // Problemas de qualidade
    strengths: string[]; // Pontos fortes
  };
  gaps: string[]; // Gaps identificados
  inconsistencies: string[]; // Inconsistências
  suggestions: string[]; // Sugestões de melhoria
  generatedAt: string;
  isOutdated?: boolean;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  documents: ProjectDocument[];
  tasks: JiraTask[];
  phases: Phase[];
  shiftLeftAnalysis?: ShiftLeftAnalysis;
  testPyramidAnalysis?: TestPyramidAnalysis;
  generalIAAnalysis?: GeneralIAAnalysis;
  tags?: string[];
  settings?: ProjectSettings;
  requirements?: Requirement[];
  rtm?: RTMEntry[];
  dashboardOverviewAnalysis?: DashboardOverviewAnalysis;
  dashboardRequirementsAnalysis?: DashboardRequirementsAnalysis;
}

export interface Comment {
  id: string;
  author: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
  mentions?: string[];
  fromJira?: boolean; // Indica se o comentário veio do Jira
}

export interface Attachment {
  id: string;
  name: string;
  type: string;
  size: number;
  url: string;
  uploadedAt: string;
}

export interface ChecklistItem {
  id: string;
  text: string;
  checked: boolean;
  required: boolean;
}

export interface ProjectSettings {
  theme?: 'light' | 'dark' | 'auto';
  notifications?: NotificationSettings;
  defaultTags?: string[];
  jiraStatuses?: Array<{ name: string; color: string } | string>; // Lista de status disponíveis no Jira com suas cores
  jiraProjectKey?: string; // Chave do projeto Jira associado
}

export interface NotificationSettings {
  email?: boolean;
  browser?: boolean;
  onBugCreated?: boolean;
  onTestFailed?: boolean;
  onDeadlineApproaching?: boolean;
  onTaskAssigned?: boolean;
  onCommentAdded?: boolean;
}

// User Preferences Types
export interface NotificationPreferences {
  bugCreated: boolean;
  testFailed: boolean;
  deadlineApproaching: boolean;
  taskAssigned: boolean;
  commentAdded: boolean;
  taskCompleted: boolean;
}

export interface KeyboardShortcutConfig {
  key: string;
  ctrl?: boolean;
  shift?: boolean;
  alt?: boolean;
}

export interface KeyboardShortcutPreferences {
  search: KeyboardShortcutConfig;
  newProject: KeyboardShortcutConfig;
  save: KeyboardShortcutConfig;
  focusSearch: KeyboardShortcutConfig;
  closeModal: KeyboardShortcutConfig;
}

export interface ExportTemplate {
  id: string;
  name: string;
  format: 'json' | 'csv' | 'markdown';
  includeMetrics: boolean;
  includeTasks: boolean;
  includeTestCases: boolean;
}

export interface ExportSchedule {
  enabled: boolean;
  frequency: 'daily' | 'weekly' | 'monthly';
  time: string; // HH:mm format
  format: 'json' | 'csv' | 'markdown';
  includeMetrics: boolean;
  includeTasks: boolean;
  includeTestCases: boolean;
  destination: 'download' | 'supabase';
  notifyOnComplete: boolean;
}

export interface ExportPreferences {
  defaultFormat: 'json' | 'csv' | 'markdown';
  defaultIncludeMetrics: boolean;
  defaultIncludeTasks: boolean;
  defaultIncludeTestCases: boolean;
  templates: ExportTemplate[];
  schedule?: ExportSchedule;
}

export interface UserPreferences {
  notifications: NotificationPreferences;
  keyboardShortcuts: KeyboardShortcutPreferences;
  export: ExportPreferences;
}