'use client';

import { cn } from '@/lib/utils';

interface ProgressRingProps {
  value: number;
  max: number;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  strokeWidth?: number;
  status?: 'healthy' | 'warning' | 'error' | 'info';
  label?: string;
  sublabel?: string;
  className?: string;
}\n
export const ProgressRing: React.FC<ProgressRingProps> = ({
  value,\n  max,\n  size = 'md',\n  strokeWidth = 8,\n  status = 'info',\n  label,\n  sublabel,\n  className\n}) => {\n  const percentage = Math.min((value / max) * 100, 100);\n  \n  const sizeConfig = {\n    sm: { container: 40, text: 'text-xs', strokeWidth: 4 },\n    md: { container: 56, text: 'text-sm', strokeWidth: 6 },\n    lg: { container: 80, text: 'text-base', strokeWidth: 8 },\n    xl: { container: 112, text: 'text-lg', strokeWidth: 10 }\n  };\n  \n  const statusColors = {\n    healthy: {\n      stroke: 'var(--success-500)',\n      text: 'var(--success-700)',\n      bg: 'var(--success-50)'\n    },\n    warning: {\n      stroke: 'var(--warning-500)',\n      text: 'var(--warning-700)',\n      bg: 'var(--warning-50)'\n    },\n    error: {\n      stroke: 'var(--error-500)',\n      text: 'var(--error-700)',\n      bg: 'var(--error-50)'\n    },\n    info: {\n      stroke: 'var(--info-500)',\n      text: 'var(--info-700)',\n      bg: 'var(--info-50)'\n    }\n  };\n  \n  const config = sizeConfig[size];\n  const radius = (config.container - config.strokeWidth) / 2;\n  const circumference = radius * 2 * Math.PI;\n  const strokeDashoffset = circumference - (percentage / 100) * circumference;\n  \n  return (\n    <div className={cn(\n      'progress-ring relative inline-block',\n      'p-2',\n      className\n    )>\n      <svg\n        width={config.container}\n        height={config.container}\n        className=\"transform -rotate-90\"\n        role=\"img\"\n        aria-label={label}\n      >\n        <circle\n          cx={config.container / 2}\n          cy={config.container / 2}\n          r={radius}\n          stroke=\"var(--border)\"\n          strokeWidth={config.strokeWidth}\n          fill=\"none\"\n        />\n        \n        <circle\n          cx={config.container / 2}\n          cy={config.container / 2}\n          r={radius}\n          stroke={statusColors[status].stroke}\n          strokeWidth={config.strokeWidth}\n          strokeDasharray={circumference}\n          strokeDashoffset={strokeDashoffset}\n          strokeLinecap=\"round\"\n          fill=\"none\"\n          className=\"transition-all duration-700 ease-in-out\"\n        />\n      </svg>\n      \n      {(label || sublabel) && (\n        <div className=\"absolute inset-0 flex flex-col items-center justify-center\">\n          {label && (\n            <div className={cn(\n              'font-bold tabular-nums',\n              config.text,\n              statusColors[status].text\n            )}>\n              {percentage.toFixed(0)}%\n            </div>\n          )}\n          {sublabel && (\n            <div className=\"text-xs text-[var(--text-muted)]\">\n              {sublabel}\n            </div>\n          )}\n        </div>\n      )}\n    </div>\n  );\n};\n